### PR TITLE
Fix backticks and tildes

### PR DESCRIPTION
**Pull request by joekur**
These are unsafe URL characters

### CODE REVIEW

**Comment by joekur** [comment]
cc @reverbdotcom/listings-dev

**Comment by joekur** [comment]
[HAL crash when viewing watchlist.](https://trello.com/c/QfLQRDEt/954-hal-crash-when-viewing-watchlist)

**Comment by jeremykay** [comment]
👍

**Comment by joekur** [comment]
We're actually not using our fork anymore. I've added a PR to the original here: https://github.com/rsl/stringex/pull/196. If we want to get this in asap though we may want to update our fork to have the latest from the original and switch back to the fork.

**Comment by joekur** [comment]
I put in a 1week reminder to see if my PR gets merged. If it doesn't by then, we can go the fork route again.

**Pull request closed without merging**
